services:
  - type: web
    name: Message Spam Classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.headless=true
